version: '3.3'

# Place the host names in /etc/hosts (mac)
# 127.0.0.1     zoo1
# 127.0.0.1     kafka1
# 127.0.0.1     kafka2
# 127.0.0.1     kafka3
# 127.0.0.1     zoonavigator-web
# 127.0.0.1     sheepkiller

services:
  zoo1:
    image: zookeeper:3.4.11
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./full-stack-build/zoo1/data:/data
      - ./full-stack-build/zoo1/datalog:/datalog

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9091"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./full-stack-build//kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
  kafka2:
    image: wurstmeister/kafka
    hostname: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./full-stack-build//kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
  kafka3:
    image: wurstmeister/kafka
    hostname: kafka3
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9093"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./full-stack-build/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1
  zoonavigator-web:
    image: elkozmon/zoonavigator-web:0.2.3
    hostname: zoonavigator-web
    ports:
     - "8004:8000"
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    links:
     - zoonavigator-api
    depends_on:
     - zoonavigator-api
    restart: unless-stopped

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:0.2.3
    environment:
      SERVER_HTTP_PORT: 9000
    restart: unless-stopped
    depends_on:
      - zoo1

  kafka-manager:
    image: sheepkiller/kafka-manager:1.3.0.4
    hostname: sheepkiller
    ports:
     - "9000:9000"
    environment:
      ZK_HOSTS: zoo1:2181
